### ISSUE TITLE
Should we have `.pop` defined already?

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/js-objects-stack-challenge#31]
Question came up as to whether or not `.pop` should already be defined in lib/stack.js on the master branch... 

I haven't read the challenge in awhile, it just came up on my way out the door, and I'm leaving this as an issue/reminder to check. I'm not sure if .pop just doesn't work and they need to fix it, if it's there by accident, or if they just get that as starter code.

```js
Stack.prototype.pop = function pop() {
  let size = this._size;
  let target = size - 1;
  let deleted;

  // remove newest value from storage and decrement size counter, only if data
  // exists
  if (size) {
    deleted = this._storage[target];
    delete this._storage[target];

    this._size--;
  }

  return deleted;
};
```

**Comment by BenGitsCode** [comment]
@payne-chris-r I removed it at first and ran through the lesson but I think it's just there to give them a start.  I made no change to it my update but this could go either way I think.

**Comment by BenGitsCode** [comment]
@J-Weeks I realized it after we sent it out is well, issue definitely should be fixed.

**Comment by gaand** [comment]
@ga-wdi-boston/core It's there because if it wasn't then this wouldn't be a challenge for most developers, it would be an impossible.  That's not the purpose of a challenge.  The implementation of pop makes this something that they can reach.

Please think carefully about what the developers are expected to know at this point.  Since a requirement of the challenge is that they aren't allowed to use array push and pop, how do you expect them to come up with a solution?

I am closing this issue as it should never have been opened.

**Comment by jrhorn424** [comment]
@ga-wdi-boston/core I'm in 100% agreement with @gaand here. If there's code somewhere, or if there's code missing, there's likely a reason.

Do not delete things from material repositories. Do not delete things from material repositories. Do not delete things from material repositories.

Ask questions.

If it wasn't clear from the instructions that pop should already have been defined, that should be tracked as a second issue.
